# Build step
FROM node:20-alpine as build

WORKDIR /app
COPY . .

RUN npm install
RUN npm run build

# Serve step
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

# Copy custom Nginx config (optional)
# COPY nginx.conf /etc/nginx/conf.d/default.conf
